name: "Setup Python"
description: "Sets up Python for use in actions with caching and copy localsettings"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv

    - uses: syphar/restore-pip-download-cache@v1
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
    - run: pip install -r requirements-dev.txt
      shell: bash
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

    - run: cp evap/settings_test.py evap/localsettings.py
      shell: bash
