name: Debug Mode Test Run

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: evap
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    name: Debug mode

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Restore venv cache
        uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv

      - name: Restore pip download cache
        uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - name: Install dependencies
        run: pip install -r requirements-dev.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - name: Add localsettings
        run: cp evap/settings_test.py evap/localsettings.py
      - name: Run tests
        run: python manage.py test --debug-mode
