name: EvaP Test Suite

on:
  push:

jobs:
  test:
    name: Test + Coverage
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run something, that does not exist
        run: deployment/run.sh
